#!/usr/bin/env -S perl -w

# Generate vectors.S, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.


print "; generated by vectors.pl - do not edit\n";
print "; handlers\n";
print "section .text\n";
print "    global alltraps\n";
print "    extern interrupt_stub\n";

for (my $i = 0; $i < 256; $i++) {
    print "    global vector$i\n";
    print "vector$i:\n";
    if (!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)) {
        print "    push dword 0\n";
    }
    print "    push dword $i\n";
    print "    jmp interrupt_stub\n";
}

print "\n; vector table\n";
print "section .data\n";
print "    global vectors\n";
print "vectors:\n";
for (my $i = 0; $i < 256; $i++) {
    print "    dd vector$i\n";
}

# sample output:
#   # handlers
#   .globl alltraps
#   .globl vector0
#   vector0:
#     pushl $0
#     pushl $0
#     jmp alltraps
#   ...
#   
#   # vector table
#   .data
#   .globl vectors
#   vectors:
#     .long vector0
#     .long vector1
#     .long vector2
#   ...

